-- 第二批公开企业资料：仅导入可访问官网入口与保守摘要。
-- 022 已在生产执行，新增企业必须使用独立迁移，避免改写历史迁移校验和。
-- 不创建用户，不写入阅读、Star、评论或 MR 行为；统计从 0 开始。

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM platform_user WHERE id = 'u-yu' AND status = 'active') THEN
    RAISE EXCEPTION '公开首发数据需要现有 active 维护者 u-yu；拒绝创建虚构用户';
  END IF;
END $$;

CREATE TEMP TABLE _public_company_seed_additional (
  project_id TEXT PRIMARY KEY, slug TEXT NOT NULL, title TEXT NOT NULL, summary TEXT NOT NULL,
  tags TEXT[] NOT NULL, company_id TEXT NOT NULL, company_name TEXT NOT NULL, company_summary TEXT NOT NULL,
  report_id TEXT NOT NULL, branch_id TEXT NOT NULL, commit_id TEXT NOT NULL, folder_id TEXT NOT NULL,
  doc_id TEXT NOT NULL, source_node_id TEXT NOT NULL, section_id TEXT NOT NULL, source_id TEXT NOT NULL,
  chunk_id TEXT NOT NULL, entity_id TEXT NOT NULL, topic_entity_id TEXT NOT NULL,
  source_title TEXT NOT NULL, publisher TEXT NOT NULL, source_url TEXT NOT NULL, snapshot TEXT NOT NULL,
  content_hash TEXT NOT NULL, captured_at TIMESTAMPTZ NOT NULL
) ON COMMIT DROP;

INSERT INTO _public_company_seed_additional VALUES
('project-youzan','youzan-retail-commerce','有赞：零售电商经营与私域产品公开研究','基于有赞官网公开入口的产品范围摘要；客户数量、收入、市场份额和价格仍需独立来源核验。',ARRAY['零售电商','商家经营','私域运营','公开资料'],'company-youzan','有赞','零售、电商经营与商家服务研究对象。','report-youzan','branch-youzan-main','commit-youzan-public-v1','folder-youzan-public','doc-youzan-public-overview','source-node-youzan-public','section-youzan-public','source-youzan-public-official','chunk-youzan-public-official','entity-youzan-public','entity-youzan-public-topic','有赞官网公开产品摘要','有赞','https://www.youzan.com/','公开官网入口及产品信息摘要：有赞官网公开展示面向商家的零售、电商经营与私域运营相关产品。此摘要仅记录企业自述，不推断客户数量、收入、市场份额或价格。','55dd22a02093c51a148f822fa6eba166577e8c4f82d12ea11a491c11a4b3c77a','2026-09-02T00:00:00Z'),
('project-fxiaoke','fxiaoke-crm','纷享销客：CRM 与销售管理产品公开研究','基于纷享销客官网公开入口的产品范围摘要；客户数量、续费率、收入和价格仍需独立来源核验。',ARRAY['CRM','销售管理','客户关系','公开资料'],'company-fxiaoke','纷享销客','企业 CRM 与销售管理研究对象。','report-fxiaoke','branch-fxiaoke-main','commit-fxiaoke-public-v1','folder-fxiaoke-public','doc-fxiaoke-public-overview','source-node-fxiaoke-public','section-fxiaoke-public','source-fxiaoke-public-official','chunk-fxiaoke-public-official','entity-fxiaoke-public','entity-fxiaoke-public-topic','纷享销客官网公开产品摘要','纷享销客','https://www.fxiaoke.com/','公开官网入口及产品信息摘要：纷享销客官网公开展示企业级 CRM、销售管理与客户关系相关产品。此摘要仅记录企业自述，不推断客户数量、续费率、收入或价格。','8cd8c488573a62b6ac420f26e7178f1b71e01bbcb8820bc5dae9529d92ec5e2d','2026-09-02T00:00:00Z'),
('project-kingdee','kingdee-enterprise-cloud','金蝶：企业管理云与 ERP 产品公开研究','基于金蝶官网公开入口的产品范围摘要；客户规模、实施效果、收入和价格仍需独立来源核验。',ARRAY['企业管理云','财务管理','ERP','公开资料'],'company-kingdee','金蝶','企业管理云与 ERP 研究对象。','report-kingdee','branch-kingdee-main','commit-kingdee-public-v1','folder-kingdee-public','doc-kingdee-public-overview','source-node-kingdee-public','section-kingdee-public','source-kingdee-public-official','chunk-kingdee-public-official','entity-kingdee-public','entity-kingdee-public-topic','金蝶官网公开产品摘要','金蝶','https://www.kingdee.com/','公开官网入口及产品信息摘要：金蝶官网公开展示企业管理云、财务管理与 ERP 相关产品。此摘要仅记录企业自述，不推断客户规模、实施效果、收入或价格。','2972864d8aa31e5b179ec31eb8cf9c7485df4c78736998bde4c2f1792ae14999','2026-09-02T00:00:00Z'),
('project-qianxin','qianxin-cybersecurity','奇安信：网络安全与安全运营产品公开研究','基于奇安信官网公开入口的产品范围摘要；安全效果、客户规模、收入和价格仍需独立来源核验。',ARRAY['网络安全','安全运营','安全服务','公开资料'],'company-qianxin','奇安信','网络安全与安全运营研究对象。','report-qianxin','branch-qianxin-main','commit-qianxin-public-v1','folder-qianxin-public','doc-qianxin-public-overview','source-node-qianxin-public','section-qianxin-public','source-qianxin-public-official','chunk-qianxin-public-official','entity-qianxin-public','entity-qianxin-public-topic','奇安信官网公开产品摘要','奇安信','https://www.qianxin.com/','公开官网入口及产品信息摘要：奇安信官网公开展示网络安全产品与服务，以及安全运营等相关能力。此摘要仅记录企业自述，不推断安全效果、客户规模、收入或价格。','92d062c024995a0ccd4e6669111057e2a7b650cd300bc1cf8464bd30247a2ac8','2026-09-02T00:00:00Z'),
('project-dbapp','dbappsecurity-data-security','安恒信息：网络与数据安全产品公开研究','基于安恒信息官网公开入口的产品范围摘要；安全效果、客户规模、收入和价格仍需独立来源核验。',ARRAY['网络安全','数据安全','安全服务','公开资料'],'company-dbapp','安恒信息','网络安全与数据安全研究对象。','report-dbapp','branch-dbapp-main','commit-dbapp-public-v1','folder-dbapp-public','doc-dbapp-public-overview','source-node-dbapp-public','section-dbapp-public','source-dbapp-public-official','chunk-dbapp-public-official','entity-dbapp-public','entity-dbapp-public-topic','安恒信息官网公开产品摘要','安恒信息','https://www.dbappsecurity.com.cn/','公开官网入口及产品信息摘要：安恒信息官网公开展示网络安全、数据安全与安全服务相关产品。此摘要仅记录企业自述，不推断安全效果、客户规模、收入或价格。','5fa5c475ad4f5e0983c063ba61b7c063f48ca2354b39b05d4148592fd43087ee','2026-09-02T00:00:00Z'),
('project-venustech','venustech-cybersecurity','启明星辰：网络安全与安全运营产品公开研究','基于启明星辰官网公开入口的产品范围摘要；安全效果、客户规模、收入和价格仍需独立来源核验。',ARRAY['网络安全','安全运营','安全服务','公开资料'],'company-venustech','启明星辰','网络安全产品与安全运营研究对象。','report-venustech','branch-venustech-main','commit-venustech-public-v1','folder-venustech-public','doc-venustech-public-overview','source-node-venustech-public','section-venustech-public','source-venustech-public-official','chunk-venustech-public-official','entity-venustech-public','entity-venustech-public-topic','启明星辰官网公开产品摘要','启明星辰','https://www.venustech.com.cn/','公开官网入口及产品信息摘要：启明星辰官网公开展示网络安全产品、安全运营与相关服务。此摘要仅记录企业自述，不推断安全效果、客户规模、收入或价格。','e34ef53a3e37320d5788315c08126ecdb003832d3dc29d69fa27f8bcefd38152','2026-09-02T00:00:00Z'),
('project-dingtalk','dingtalk-collaboration','钉钉：企业协同与组织管理产品公开研究','基于钉钉官网公开入口的产品范围摘要；客户规模、使用效果、收入和价格仍需独立来源核验。',ARRAY['协同办公','组织管理','企业数字化','公开资料'],'company-dingtalk','钉钉','企业协同办公与组织管理研究对象。','report-dingtalk','branch-dingtalk-main','commit-dingtalk-public-v1','folder-dingtalk-public','doc-dingtalk-public-overview','source-node-dingtalk-public','section-dingtalk-public','source-dingtalk-public-official','chunk-dingtalk-public-official','entity-dingtalk-public','entity-dingtalk-public-topic','钉钉官网公开产品摘要','钉钉','https://www.dingtalk.com/','公开官网入口及产品信息摘要：钉钉官网公开展示企业协同办公、组织管理与数字化工作相关产品。此摘要仅记录企业自述，不推断客户规模、使用效果、收入或价格。','46226b2a09a7bf8c63d5fd50afe1fe72e3096d4d404ec1ebf10820b1814682f0','2026-09-02T00:00:00Z'),
('project-lark','lark-team-collaboration','Lark：团队协作与沟通产品公开研究','基于 Lark 官网公开入口的产品范围摘要；客户规模、使用效果、收入和价格仍需独立来源核验。',ARRAY['团队协作','沟通','工作管理','公开资料'],'company-lark','Lark','团队协作与沟通产品研究对象。','report-lark','branch-lark-main','commit-lark-public-v1','folder-lark-public','doc-lark-public-overview','source-node-lark-public','section-lark-public','source-lark-public-official','chunk-lark-public-official','entity-lark-public','entity-lark-public-topic','Lark 官网公开产品摘要','Lark','https://www.larksuite.com/','公开官网入口及产品信息摘要：Lark 官网公开展示团队协作、沟通与工作管理相关产品。此摘要仅记录企业自述，不推断客户规模、使用效果、收入或价格。','c3709bcedc69ee8d12c516c78ea41822e641b39e9f1a569282151a5127221e46','2026-09-02T00:00:00Z');

INSERT INTO knowledge_project (id, owner_user_id, slug, title, summary, visibility, status, license, default_branch_name, published_at, created_at, updated_at, category, tags, verification, verification_note)
SELECT project_id,'u-yu',slug,title,summary,'public','published','cc-by-4.0','main',captured_at,captured_at,captured_at,'企业',tags,'needs_verification','只包含官网公开入口与摘要；商业数据和效果结论仍待独立证据核验。' FROM _public_company_seed_additional ON CONFLICT (id) DO NOTHING;
INSERT INTO project_member (project_id,user_id,role,created_at) SELECT project_id,'u-yu','owner',captured_at FROM _public_company_seed_additional ON CONFLICT DO NOTHING;
INSERT INTO knowledge_branch (id,project_id,name,owner_user_id,is_protected,status,version,created_at,updated_at) SELECT branch_id,project_id,'main',NULL,TRUE,'active',1,captured_at,captured_at FROM _public_company_seed_additional ON CONFLICT (id) DO NOTHING;
INSERT INTO knowledge_commit (id,project_id,branch_id,parent_commit_id,author_user_id,message,ai_assisted,idempotency_key,change_summary,created_at) SELECT commit_id,project_id,branch_id,NULL,'u-yu','导入公开官网摘要（待核验）',FALSE,'seed:public-company:'||slug||':v1',jsonb_build_object('seed',true,'sourceType','official_website','evidenceState','needs_verification'),captured_at FROM _public_company_seed_additional ON CONFLICT (id) DO NOTHING;
UPDATE knowledge_branch b SET head_commit_id=s.commit_id,version=GREATEST(b.version,1),updated_at=s.captured_at FROM _public_company_seed_additional s WHERE b.id=s.branch_id;
INSERT INTO knowledge_node (id,project_id,kind,created_by_user_id,created_at) SELECT folder_id,project_id,'folder','u-yu',captured_at FROM _public_company_seed_additional UNION ALL SELECT doc_id,project_id,'document','u-yu',captured_at FROM _public_company_seed_additional UNION ALL SELECT source_node_id,project_id,'source','u-yu',captured_at FROM _public_company_seed_additional ON CONFLICT (id) DO NOTHING;
INSERT INTO knowledge_node_state (project_id,branch_id,node_id,parent_node_id,name,position,deleted_at,updated_at) SELECT project_id,branch_id,folder_id,NULL::TEXT,'公开资料',1,NULL::TIMESTAMPTZ,captured_at FROM _public_company_seed_additional UNION ALL SELECT project_id,branch_id,doc_id,folder_id,'产品范围与证据边界',1,NULL::TIMESTAMPTZ,captured_at FROM _public_company_seed_additional UNION ALL SELECT project_id,branch_id,source_node_id,NULL::TEXT,source_title,2,NULL::TIMESTAMPTZ,captured_at FROM _public_company_seed_additional ON CONFLICT (branch_id,node_id) DO NOTHING;
INSERT INTO document_revision (id,project_id,node_id,branch_id,commit_id,content,content_text,content_hash,created_by_user_id,created_at) SELECT 'revision-'||project_id||'-public-v1',project_id,doc_id,branch_id,commit_id,'{"type":"doc","content":[]}'::jsonb,summary||E'\n\n证据状态：needs_verification。来源是企业公开官网入口和人工摘要；未从摘要推断商业指标。',content_hash,'u-yu',captured_at FROM _public_company_seed_additional ON CONFLICT (id) DO NOTHING;
INSERT INTO content_attribution (id,project_id,node_id,block_id,origin_commit_id,last_touch_commit_id,contributor_user_id,active,created_at,updated_at) SELECT 'attr-'||project_id||'-public',project_id,doc_id,doc_id||':block:1',commit_id,commit_id,'u-yu',TRUE,captured_at,captured_at FROM _public_company_seed_additional ON CONFLICT DO NOTHING;

INSERT INTO company (id,name,kind,summary,tags,created_at,updated_at) SELECT company_id,company_name,'company',company_summary,tags,captured_at,captured_at FROM _public_company_seed_additional ON CONFLICT (id) DO NOTHING;
INSERT INTO report (id,company_id,title,status,current_version,created_at,updated_at) SELECT report_id,company_id,title,'draft',1,captured_at,captured_at FROM _public_company_seed_additional ON CONFLICT (id) DO NOTHING;
INSERT INTO report_section (id,report_id,parent_section_id,heading,anchor,level,position,content,evidence_state,updated_at) SELECT section_id,report_id,NULL,'公开摘要与证据边界','public-summary-evidence',1,1,snapshot||E'\n\n该段仅记录官网公开表述；商业数据、客户规模和效果结论需要独立来源。','needs_verification',captured_at FROM _public_company_seed_additional ON CONFLICT (id) DO NOTHING;
INSERT INTO source (id,report_id,title,kind,url,language,state,captured_at,content_hash,snapshot,evidence_state,metadata) SELECT source_id,report_id,source_title,'web',source_url,'zh','active',captured_at,content_hash,snapshot,'needs_verification',jsonb_build_object('sourceType','official_website','publisher',publisher,'capturedAt',captured_at,'licenseNote','公开官网页面；仅引用与研究相关的短摘要，遵守原站条款。','retrievalMode','curated_url_summary') FROM _public_company_seed_additional ON CONFLICT (id) DO NOTHING;
INSERT INTO source_chunk (id,source_id,parent_section_id,heading_path,position,page,start_offset,end_offset,text,contextual_prefix,content_hash) SELECT chunk_id,source_id,section_id,ARRAY['公开官网','产品范围']::TEXT[],1,NULL,0,char_length(snapshot),snapshot,'企业公开官网摘要；证据状态：needs_verification；不能据此推断商业指标。',content_hash FROM _public_company_seed_additional ON CONFLICT (id) DO NOTHING;
INSERT INTO citation (id,report_id,section_id,source_id,chunk_id,quote,evidence_state,created_at) SELECT 'citation-'||project_id||'-public',report_id,section_id,source_id,chunk_id,snapshot,'needs_verification',captured_at FROM _public_company_seed_additional ON CONFLICT (id) DO NOTHING;
INSERT INTO entity (id,report_id,kind,name,normalized_name,source_id,evidence_state,attributes,created_at) SELECT entity_id,report_id,'company',company_name,lower(company_name),source_id,'fact',jsonb_build_object('officialUrl',source_url,'sourceType','official_website'),captured_at FROM _public_company_seed_additional ON CONFLICT DO NOTHING;
INSERT INTO entity (id,report_id,kind,name,normalized_name,source_id,evidence_state,attributes,created_at) SELECT topic_entity_id,report_id,'industry',tags[1],lower(slug||'-topic'),source_id,'needs_verification',jsonb_build_object('officialUrl',source_url),captured_at FROM _public_company_seed_additional ON CONFLICT DO NOTHING;
INSERT INTO relation_edge (id,report_id,from_entity_id,to_entity_id,relation,source_id,evidence_state,created_at) SELECT 'edge-'||project_id||'-public-scope',report_id,entity_id,topic_entity_id,'官网自述产品范围',source_id,'fact',captured_at FROM _public_company_seed_additional ON CONFLICT (id) DO NOTHING;
INSERT INTO project_stats (project_id,unique_readers,updated_at) SELECT project_id,0,captured_at FROM _public_company_seed_additional ON CONFLICT (project_id) DO NOTHING;
